server:
  port: 10001
spring:
  application:
    name: mw-registry
eureka:
  client:
      register-with-eureka: true
      fetch-registry: false
      service-url:
        defaultZone: http://127.0.0.1:10001/eureka/